kind: Secret
apiVersion: v1
metadata:
  name: regcred
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMub2NwLWJtLnBvYy5jbG91ZCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJyM2RoNHQxISIsImF1dGgiOiJZV1J0YVc0NmNqTmthRFIwTVNFPSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson
