apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-app
  name: poc-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: poc-app
